info.onCountdownEnd(function () {
    game.splash("Welcome to Oscar's Shark Game!")
    game.over(true, effects.melt)
})
function Make_Sharks () {
    for (let index = 0; index < 10 - sprites.allOfKind(SpriteKind.Food).length; index++) {
        mySprite = sprites.create(img`
            .............ccfff..............
            ...........ccddbcf..............
            ..........ccddbbf...............
            ..........fccbbcf...............
            .....fffffccccccff.........ccc..
            ...ffbbbbbbbcbbbbcfff....ccbbc..
            ..fbbbbbbbbcbcbbbbcccff.cdbbc...
            ffbbbbbbffbbcbcbbbcccccfcdbbf...
            fbcbbb11ff1bcbbbbbcccccffbbf....
            fbbb11111111bbbbbcccccccbbcf....
            .fb11133cc11bbbbcccccccccccf....
            ..fccc31c111bbbcccccbdbffbbcf...
            ...fc13c111cbbbfcddddcc..fbbf...
            ....fccc111fbdbbccdcc.....fbbf..
            ........ccccfcdbbcc........fff..
            .............fffff..............
            `, SpriteKind.Food)
        mySprite.y = randint(20, 100)
        mySprite.x = randint(20, 120)
        mySprite.vx = randint(-50, 50)
        mySprite.vy = randint(-50, 50)
        mySprite.setBounceOnWall(true)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    otherSprite.destroy(effects.fire, 200)
    music.thump.play()
    info.changeScoreBy(1)
    sharkCount += -1
    if (sharkCount == 0) {
        sharkCount = 10
    }
})
let sharkCount = 0
let mySprite: Sprite = null
Make_Sharks()
let mySprite2 = sprites.create(img`
    ...........fffffff...ccfff..........
    ..........fbbbbbbbffcbbbbf..........
    ..........fbb111bbbbbffbf...........
    ..........fb11111ffbbbbff...........
    ..........f1cccc1ffbbbbbcff.........
    ..........ffc1c1c1bbcbcbcccf........
    ...........fcc3331bbbcbcbcccf..ccccc
    ............c333c1bbbcbcbccccfcddbbc
    ............c333c1bbbbbbbcccccddbcc.
    ............c333c11bbbbbccccccbbcc..
    ...........cc331c11bbbbccccccfbccf..
    ...........cc13c11cbbbcccccbbcfccf..
    ...........c111111cbbbfdddddc.fbbcf.
    ............cc1111fbdbbfdddc...fbbf.
    ..............cccfffbdbbfcc.....fbbf
    ....................fffff........fff
    `, SpriteKind.Player)
controller.moveSprite(mySprite2)
info.startCountdown(30)
game.onUpdate(function () {
    for (let value of sprites.allOfKind(SpriteKind.Food)) {
        if (value.vx > 0) {
            value.setImage(img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `)
        } else {
            value.setImage(img`
                .............ccfff..............
                ...........ccddbcf..............
                ..........ccddbbf...............
                ..........fccbbcf...............
                .....fffffccccccff.........ccc..
                ...ffbbbbbbbcbbbbcfff....ccbbc..
                ..fbbbbbbbbcbcbbbbcccff.cdbbc...
                ffbbbbbbffbbcbcbbbcccccfcdbbf...
                fbcbbb11ff1bcbbbbbcccccffbbf....
                fbbb11111111bbbbbcccccccbbcf....
                .fb11133cc11bbbbcccccccccccf....
                ..fccc31c111bbbcccccbdbffbbcf...
                ...fc13c111cbbbfcddddcc..fbbf...
                ....fccc111fbdbbccdcc.....fbbf..
                ........ccccfcdbbcc........fff..
                .............fffff..............
                `)
        }
    }
    if (mySprite2.vx > 0) {
        mySprite2.setImage(img`
            ..........fffcc...fffffff...........
            ..........fbbbbcffbbbbbbbf..........
            ...........fbffbbbbb111bbf..........
            ...........ffbbbbff11111bf..........
            .........ffcbbbbbff1cccc1f..........
            ........fcccbcbcbb1c1c1cff..........
            ccccc..fcccbcbcbbb1333ccf...........
            cbbddcfccccbcbcbbb1c333c............
            .ccbddcccccbbbbbbb1c333c............
            ..ccbbccccccbbbbb11c333c............
            ..fccbfccccccbbbb11c133cc...........
            ..fccfcbbcccccbbbc11c31cc...........
            .fcbbf.cdddddfbbbc111111c...........
            .fbbf...cdddfbbdbf1111cc............
            fbbf.....ccfbbdbfffccc..............
            fff........fffff....................
            `)
    } else if (mySprite2.vx < 0) {
        mySprite2.setImage(img`
            ...........fffffff...ccfff..........
            ..........fbbbbbbbffcbbbbf..........
            ..........fbb111bbbbbffbf...........
            ..........fb11111ffbbbbff...........
            ..........f1cccc1ffbbbbbcff.........
            ..........ffc1c1c1bbcbcbcccf........
            ...........fcc3331bbbcbcbcccf..ccccc
            ............c333c1bbbcbcbccccfcddbbc
            ............c333c1bbbbbbbcccccddbcc.
            ............c333c11bbbbbccccccbbcc..
            ...........cc331c11bbbbccccccfbccf..
            ...........cc13c11cbbbcccccbbcfccf..
            ...........c111111cbbbfdddddc.fbbcf.
            ............cc1111fbdbbfdddc...fbbf.
            ..............cccfffbdbbfcc.....fbbf
            ....................fffff........fff
            `)
    }
})
game.onUpdateInterval(2000, function () {
    Make_Sharks()
})
